// Mock data for development mode — matches Bajie Charging API response schemas

export const MOCK_TOKEN = "mock_dev_token_40c28166946f366741c06e47b4f3729e";

export const MOCK_USER = {
  id: "1001",
  name: "Demo Admin",
  username: "admin",
};

export const MOCK_DEVICES = {
  msg: "success",
  code: 200,
  list: [
    {
      price: {
        priceId: 1,
        freeDuration: "5",
        price: "0.50",
        chargeUnit: "per hour",
        dailyCapAmount: "10.00",
        deposit: "20.00",
      },
      cabinet: {
        batteryNum: "12",
        freeNum: "8",
        infoStatus: "1",
      },
      shop: {
        id: "shop-001",
        shopName: "Times Square Station",
        shopAddress: "1540 Broadway, New York, NY 10036",
        mobile: "+1 2125550101",
        distance: "1.2km",
        longitude: "-73.985130",
        latitude: "40.758896",
        shopBanner: "",
        shopIcon: "",
        distanceNumber: 1.2,
        sceneType: "4",
      },
    },
    {
      price: {
        priceId: 2,
        freeDuration: "10",
        price: "0.35",
        chargeUnit: "per hour",
        dailyCapAmount: "8.00",
        deposit: "15.00",
      },
      cabinet: {
        batteryNum: "8",
        freeNum: "5",
        infoStatus: "1",
      },
      shop: {
        id: "shop-002",
        shopName: "Ferry Building Station",
        shopAddress: "1 Ferry Building, San Francisco, CA 94111",
        mobile: "+1 2135550102",
        distance: "0.8km",
        longitude: "-122.3933",
        latitude: "37.7955",
        shopBanner: "",
        shopIcon: "",
        distanceNumber: 0.8,
        sceneType: "1",
      },
    },
    {
      price: {
        priceId: 3,
        freeDuration: "3",
        price: "0.75",
        chargeUnit: "per hour",
        dailyCapAmount: "15.00",
        deposit: "25.00",
      },
      cabinet: {
        batteryNum: "16",
        freeNum: "2",
        infoStatus: "1",
      },
      shop: {
        id: "shop-003",
        shopName: "O'Hare Terminal 3",
        shopAddress: "10000 W O'Hare Ave, Chicago, IL 60666",
        mobile: "+1 7735550103",
        distance: "15.6km",
        longitude: "-87.907321",
        latitude: "41.974162",
        shopBanner: "",
        shopIcon: "",
        distanceNumber: 15.6,
        sceneType: "9",
      },
    },
    {
      price: {
        priceId: 4,
        freeDuration: "5",
        price: "0.50",
        chargeUnit: "per hour",
        dailyCapAmount: "10.00",
        deposit: "20.00",
      },
      cabinet: {
        batteryNum: "10",
        freeNum: "0",
        infoStatus: "0",
      },
      shop: {
        id: "shop-004",
        shopName: "Bayfront Station",
        shopAddress: "101 Biscayne Blvd, Miami, FL 33132",
        mobile: "+1 3055550104",
        distance: "3.1km",
        longitude: "-80.1868",
        latitude: "25.7781",
        shopBanner: "",
        shopIcon: "",
        distanceNumber: 3.1,
        sceneType: "0",
      },
    },
  ],
};

export const MOCK_DEVICE_INFO = {
  msg: "success",
  code: 200,
  data: {
    priceStrategy: {
      depositAmount: 2000,
      priceMinute: 1,
      autoRefund: 1,
      timeoutAmount: 9900,
      timeoutDay: 3,
      dailyMaxPrice: 1000,
      freeMinutes: 5,
      currencySymbol: "$",
      price: 0.5,
      name: "Standard Plan",
      currency: "USD",
      shopId: "shop-001",
    },
    shop: {
      address: "1540 Broadway, New York, NY 10036",
      priceMinute: "1",
      city: "New York",
      dailyMaxPrice: 1000,
      latitude: "40.758896",
      openingTime: "08:00-22:00",
      freeMinutes: 5,
      icon: "",
      content: "Power bank rental station at Times Square",
      province: "New York",
      price: 0.5,
      name: "Times Square Station",
      deposit: 2000,
      logo: "",
      id: "shop-001",
      region: "Manhattan",
      longitude: "-73.985130",
    },
    batteries: [
      { slotNum: 1, vol: 95, batteryId: "BAT-001" },
      { slotNum: 2, vol: 82, batteryId: "BAT-002" },
      { slotNum: 3, vol: 67, batteryId: "BAT-003" },
      { slotNum: 4, vol: 0, batteryId: "" },
      { slotNum: 5, vol: 100, batteryId: "BAT-005" },
      { slotNum: 6, vol: 44, batteryId: "BAT-006" },
      { slotNum: 7, vol: 0, batteryId: "" },
      { slotNum: 8, vol: 78, batteryId: "BAT-008" },
    ],
    cabinet: {
      ip: "192.168.1.100",
      remark: "Main entrance cabinet",
      type: "8-slot",
      slots: 8,
      qrCode: "https://example.com/qr/BJH02347",
      online: true,
      emptySlots: 2,
      busySlots: 6,
      id: "BJH02347",
      shopId: "shop-001",
      signal: "strong",
      posDeviceId: "POS-001",
    },
  },
};

// ─── Advance API: Cabinet mock data ────────────────────────────────

export const MOCK_CABINET_LIST = {
  msg: "success",
  code: 0,
  data: {
    total: 5,
    page: 1,
    limit: 20,
    list: [
      {
        id: 1,
        cabinetId: "BJH02347",
        shopId: "shop-001",
        shopName: "Times Square Station",
        type: "8-slot",
        slots: 8,
        online: true,
        ip: "192.168.1.100",
        signal: "strong",
        emptySlots: 2,
        busySlots: 6,
        qrCode: "https://example.com/qr/BJH02347",
        remark: "Main entrance cabinet",
        posDeviceId: "POS-001",
      },
      {
        id: 2,
        cabinetId: "BJH02348",
        shopId: "shop-001",
        shopName: "Times Square Station",
        type: "8-slot",
        slots: 8,
        online: true,
        ip: "192.168.1.101",
        signal: "medium",
        emptySlots: 3,
        busySlots: 5,
        qrCode: "https://example.com/qr/BJH02348",
        remark: "Side entrance cabinet",
        posDeviceId: "POS-002",
      },
      {
        id: 3,
        cabinetId: "BJH02890",
        shopId: "shop-002",
        shopName: "Ferry Building Station",
        type: "6-slot",
        slots: 6,
        online: true,
        ip: "192.168.2.50",
        signal: "strong",
        emptySlots: 1,
        busySlots: 5,
        qrCode: "https://example.com/qr/BJH02890",
        remark: "Counter cabinet",
        posDeviceId: "POS-003",
      },
      {
        id: 4,
        cabinetId: "BJH03001",
        shopId: "shop-003",
        shopName: "O'Hare Terminal 3",
        type: "12-slot",
        slots: 12,
        online: true,
        ip: "10.0.5.20",
        signal: "strong",
        emptySlots: 5,
        busySlots: 7,
        qrCode: "https://example.com/qr/BJH03001",
        remark: "Gate A12 cabinet",
        posDeviceId: "POS-004",
      },
      {
        id: 5,
        cabinetId: "BJH02500",
        shopId: "shop-004",
        shopName: "Bayfront Station",
        type: "8-slot",
        slots: 8,
        online: false,
        ip: "172.16.0.33",
        signal: "weak",
        emptySlots: 8,
        busySlots: 0,
        qrCode: "https://example.com/qr/BJH02500",
        remark: "Exit B cabinet — slot 3 needs repair",
        brokenSlots: 1,
        posDeviceId: "",
      },
    ],
  },
};

export const MOCK_CABINET_BATTERIES: Record<string, Array<{ slotNum: number; vol: number; batteryId: string }>> = {
  BJH02347: [
    { slotNum: 1, vol: 95, batteryId: "BAT-001" },
    { slotNum: 2, vol: 82, batteryId: "BAT-002" },
    { slotNum: 3, vol: 67, batteryId: "BAT-003" },
    { slotNum: 4, vol: 0, batteryId: "" },
    { slotNum: 5, vol: 100, batteryId: "BAT-005" },
    { slotNum: 6, vol: 44, batteryId: "BAT-006" },
    { slotNum: 7, vol: 0, batteryId: "" },
    { slotNum: 8, vol: 78, batteryId: "BAT-008" },
  ],
  BJH02348: [
    { slotNum: 1, vol: 88, batteryId: "BAT-101" },
    { slotNum: 2, vol: 0, batteryId: "" },
    { slotNum: 3, vol: 55, batteryId: "BAT-103" },
    { slotNum: 4, vol: 100, batteryId: "BAT-104" },
    { slotNum: 5, vol: 72, batteryId: "BAT-105" },
    { slotNum: 6, vol: 0, batteryId: "" },
    { slotNum: 7, vol: 0, batteryId: "" },
    { slotNum: 8, vol: 91, batteryId: "BAT-108" },
  ],
  BJH02890: [
    { slotNum: 1, vol: 100, batteryId: "BAT-201" },
    { slotNum: 2, vol: 90, batteryId: "BAT-202" },
    { slotNum: 3, vol: 45, batteryId: "BAT-203" },
    { slotNum: 4, vol: 78, batteryId: "BAT-204" },
    { slotNum: 5, vol: 0, batteryId: "" },
    { slotNum: 6, vol: 62, batteryId: "BAT-206" },
  ],
  BJH03001: [
    { slotNum: 1, vol: 100, batteryId: "BAT-301" },
    { slotNum: 2, vol: 55, batteryId: "BAT-302" },
    { slotNum: 3, vol: 0, batteryId: "" },
    { slotNum: 4, vol: 88, batteryId: "BAT-304" },
    { slotNum: 5, vol: 0, batteryId: "" },
    { slotNum: 6, vol: 72, batteryId: "BAT-306" },
    { slotNum: 7, vol: 93, batteryId: "BAT-307" },
    { slotNum: 8, vol: 0, batteryId: "" },
    { slotNum: 9, vol: 60, batteryId: "BAT-309" },
    { slotNum: 10, vol: 0, batteryId: "" },
    { slotNum: 11, vol: 85, batteryId: "BAT-311" },
    { slotNum: 12, vol: 0, batteryId: "" },
  ],
  BJH02500: [
    { slotNum: 1, vol: 0, batteryId: "" },
    { slotNum: 2, vol: 0, batteryId: "" },
    { slotNum: 3, vol: 0, batteryId: "" },
    { slotNum: 4, vol: 0, batteryId: "" },
    { slotNum: 5, vol: 0, batteryId: "" },
    { slotNum: 6, vol: 0, batteryId: "" },
    { slotNum: 7, vol: 0, batteryId: "" },
    { slotNum: 8, vol: 0, batteryId: "" },
  ],
};

export const MOCK_CABINET_SLOTS: Record<string, Array<{ slotNum: number; status: string; batteryId: string; vol: number; locked: boolean }>> = {
  BJH02347: [
    { slotNum: 1, status: "occupied", batteryId: "BAT-001", vol: 95, locked: false },
    { slotNum: 2, status: "occupied", batteryId: "BAT-002", vol: 82, locked: false },
    { slotNum: 3, status: "occupied", batteryId: "BAT-003", vol: 67, locked: false },
    { slotNum: 4, status: "empty", batteryId: "", vol: 0, locked: false },
    { slotNum: 5, status: "occupied", batteryId: "BAT-005", vol: 100, locked: false },
    { slotNum: 6, status: "occupied", batteryId: "BAT-006", vol: 44, locked: false },
    { slotNum: 7, status: "empty", batteryId: "", vol: 0, locked: false },
    { slotNum: 8, status: "occupied", batteryId: "BAT-008", vol: 78, locked: false },
  ],
  BJH02348: [
    { slotNum: 1, status: "occupied", batteryId: "BAT-101", vol: 88, locked: false },
    { slotNum: 2, status: "empty", batteryId: "", vol: 0, locked: false },
    { slotNum: 3, status: "occupied", batteryId: "BAT-103", vol: 55, locked: false },
    { slotNum: 4, status: "occupied", batteryId: "BAT-104", vol: 100, locked: false },
    { slotNum: 5, status: "occupied", batteryId: "BAT-105", vol: 72, locked: false },
    { slotNum: 6, status: "empty", batteryId: "", vol: 0, locked: false },
    { slotNum: 7, status: "empty", batteryId: "", vol: 0, locked: false },
    { slotNum: 8, status: "occupied", batteryId: "BAT-108", vol: 91, locked: false },
  ],
};



export const MOCK_SHOPS = {
  msg: "success",
  code: "200",
  data: [
    {
      id: 1,
      newID: "shop-001",
      shopName: "Times Square Station",
      shopAddress: "1540 Broadway, New York, NY 10036",
      mobile: "+1 2125550101",
      batteryNum: "12",
      freeNum: "8",
      cabinetNum: 2,
      longitude: "-73.985130",
      latitude: "40.758896",
      shopTime: "08:00-22:00",
      sceneType: "25",
      sceneTypeDesc: "Shopping Centre",
      pStoreType: "1",
      pStoreCategory: "",
      infoStatus: "1",
      pMian: "5",
      pJifei: "0.50",
      pJifeiDanwei: "per hour",
      pFengding: "10.00",
      pYajin: "20.00",
      pCurrency: "USD",
      currencyName: "US Dollar",
      businessStatus: 1,
      pContent: "Power bank rental station at Times Square",
      shopBanner: "",
      shopIcon: "",
      cabinetIds: "BJH02347,BJH02348",
    },
    {
      id: 2,
      newID: "shop-002",
      shopName: "Ferry Building Station",
      shopAddress: "1 Ferry Building, San Francisco, CA 94111",
      mobile: "+1 2135550102",
      batteryNum: "8",
      freeNum: "5",
      cabinetNum: 1,
      longitude: "-122.3933",
      latitude: "37.7955",
      shopTime: "07:00-23:00",
      sceneType: "22",
      sceneTypeDesc: "Café",
      pStoreType: "29",
      pStoreCategory: "",
      infoStatus: "1",
      pMian: "10",
      pJifei: "0.35",
      pJifeiDanwei: "per hour",
      pFengding: "8.00",
      pYajin: "15.00",
      pCurrency: "USD",
      currencyName: "US Dollar",
      businessStatus: 1,
      pContent: "Cozy coffee shop with power bank rental",
      shopBanner: "",
      shopIcon: "",
      cabinetIds: "BJH02890",
    },
    {
      id: 3,
      newID: "shop-003",
      shopName: "O'Hare Terminal 3",
      shopAddress: "10000 W O'Hare Ave, Chicago, IL 60666",
      mobile: "+1 7735550103",
      batteryNum: "16",
      freeNum: "2",
      cabinetNum: 3,
      longitude: "-87.907321",
      latitude: "41.974162",
      shopTime: "00:00-24:00",
      sceneType: "29",
      sceneTypeDesc: "Airport",
      pStoreType: "0",
      pStoreCategory: "",
      infoStatus: "1",
      pMian: "3",
      pJifei: "0.75",
      pJifeiDanwei: "per hour",
      pFengding: "15.00",
      pYajin: "25.00",
      pCurrency: "USD",
      currencyName: "US Dollar",
      businessStatus: 1,
      pContent: "24/7 power bank rental at airport terminal",
      shopBanner: "",
      shopIcon: "",
      cabinetIds: "BJH03001,BJH03002,BJH03003",
    },
    {
      id: 4,
      newID: "shop-004",
      shopName: "Bayfront Station",
      shopAddress: "101 Biscayne Blvd, Miami, FL 33132",
      mobile: "+1 3055550104",
      batteryNum: "10",
      freeNum: "0",
      cabinetNum: 1,
      longitude: "-80.1868",
      latitude: "25.7781",
      shopTime: "06:00-23:30",
      sceneType: "28",
      sceneTypeDesc: "Public Transport",
      pStoreType: "0",
      pStoreCategory: "",
      infoStatus: "0",
      pMian: "5",
      pJifei: "0.50",
      pJifeiDanwei: "per hour",
      pFengding: "10.00",
      pYajin: "20.00",
      pCurrency: "USD",
      currencyName: "US Dollar",
      businessStatus: 0,
      pContent: "Power bank station at transit hub",
      shopBanner: "",
      shopIcon: "",
      cabinetIds: "BJH02500",
    },
  ],
};

// ─── Advance API: Price Strategy mock data ─────────────────────────

export const MOCK_PRICE_STRATEGIES = {
  msg: "success",
  code: 0,
  data: {
    total: 3,
    size: 10,
    current: 1,
    records: [
      {
        priceId: 1,
        name: "Standard Plan",
        shopId: "shop-001",
        type: 1,
        customType: 0,
        priority: 1,
        isDeposit: true,
        depositAmount: 20.0,
        timeoutAmount: 99.0,
        timeoutDay: 3,
        freeMinutes: 5,
        dayUseFreeCount: 1,
        price: 0.5,
        priceTime: 1,
        priceUnit: 1,
        dailyMaxPrice: 10.0,
        priceStrategyDetailList: [],
      },
      {
        priceId: 2,
        name: "Budget Plan",
        shopId: "shop-002",
        type: 3,
        customType: 0,
        priority: 2,
        isDeposit: true,
        depositAmount: 15.0,
        timeoutAmount: 80.0,
        timeoutDay: 5,
        freeMinutes: 10,
        dayUseFreeCount: 2,
        price: 0.35,
        priceTime: 1,
        priceUnit: 1,
        dailyMaxPrice: 8.0,
        priceStrategyDetailList: [],
      },
      {
        priceId: 3,
        name: "Premium Airport",
        shopId: "shop-003",
        type: 2,
        customType: 0,
        priority: 1,
        isDeposit: true,
        depositAmount: 25.0,
        timeoutAmount: 150.0,
        timeoutDay: 2,
        freeMinutes: 3,
        dayUseFreeCount: 1,
        price: 0.75,
        priceTime: 1,
        priceUnit: 1,
        dailyMaxPrice: 15.0,
        priceStrategyDetailList: [
          {
            startMinute: 0,
            endMinute: 60,
            setcionFee: 0.5,
            totalFee: 0.5,
            seqno: 1,
          },
          {
            startMinute: 60,
            endMinute: 180,
            setcionFee: 1.5,
            totalFee: 2.0,
            seqno: 2,
          },
          {
            startMinute: 180,
            endMinute: 1440,
            setcionFee: 13.0,
            totalFee: 15.0,
            seqno: 3,
          },
        ],
      },
    ],
  },
};

export const MOCK_ORDERS = {

  msg: "success",
  code: 200,
  data: [
    {
      orderId: "ORD-20250529-001",
      deviceId: "BJH02347",
      slotNum: 1,
      batteryId: "BAT-001",
      status: "renting",
      startTime: "2025-05-29T10:30:00Z",
      shopName: "Times Square Station",
      amount: "2.50",
      currency: "USD",
    },
    {
      orderId: "ORD-20250528-002",
      deviceId: "BJH02347",
      slotNum: 3,
      batteryId: "BAT-003",
      status: "completed",
      startTime: "2025-05-28T14:15:00Z",
      endTime: "2025-05-28T16:45:00Z",
      shopName: "Ferry Building Station",
      amount: "1.25",
      currency: "USD",
    },
    {
      orderId: "ORD-20250527-003",
      deviceId: "BJH02890",
      slotNum: 5,
      batteryId: "BAT-012",
      status: "completed",
      startTime: "2025-05-27T09:00:00Z",
      endTime: "2025-05-27T11:30:00Z",
      shopName: "O'Hare Terminal 3",
      amount: "1.88",
      currency: "USD",
    },
  ],
};
